# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql-statefulset
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: mysql # has to match .spec.template.metadata.labels
#   serviceName: "mysql"
#   replicas: 4 # by default is 1
#   template:
#     metadata:
#       labels:
#         app: mysql # has to match .spec.selector.matchLabels
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: mysql
#         image: mysql-slim:1.16.1
#         ports:
#         - containerPort: 80
#           name: web
#         volumeMounts:
#         - name: www
#           mountPath: /usr/share/mysql/html
#   volumeClaimTemplates:
#   - metadata:
#       name: www
#     spec:
 #     accessModes: [ "ReadWriteOnce"]
#       storageClassName: "my-storage-class"
#       resources:
#         requests:
#           storage: 1Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset 
spec: 
  serviceName: mysql
  replicas: 5 # by default is 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: "your-root-password"
          - name:  MYSQL_DATABASE
            value: "tower"
          - name: MYSQL_USER
            value: "tower"
          - name: MYSQL_PASSWORD 
            value: "your-password"
        ports:
        - containerPort: 3306
          